Add handling of non-standard ports
TeamPiped/Piped-Docker pull request #39
Opened 2024-04-28 08:10 UTC by BenjaminSalzberg

The default port instantiated by the self-hosting system sues port 8080. There might be users who already use that port for something else. As such, this should allow for an easy set up for those users who might wish to use a different port. 
Please note that I was unable to test the caddy set up, as such it might not function correctly. However, this appears to work for nginx.

2024-04-28 23:55 UTC, FireMasterK requested changes
Hi there, thanks for the contribution!

Please only change the external exposed port for the nginx docker-compose file, where this change would make sense. It also needs to default to port 8080 by default if there's no port specified.

2024-04-28 23:55 UTC, FireMasterK commented on template/docker-compose.nginx.yml
> -            - "8080:80"
Only this change should remain, the rest of the changes should be reverted.

2024-05-01 02:03 UTC, BenjaminSalzberg commented
The nginx docker file is now the only edited docker file. Additionally, when using caddy the bash script will not ask for a custom port.

2025-01-22 16:47 UTC, Bnyro commented
Due to the many changes to the installation process, this PR should probably be started from scratch if still desired.

2025-01-22 16:47 UTC, closed without merging